name: Top Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3 
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bash -s' << 'ENDSSH'
        cd /var/www
        ssh-agent bash
        chmod -R 600 deploy
        ssh-add deploy
        cd /mnt/volume_sgp1_production/api-tose-blog
        git config --global --add safe.directory /mnt/volume_sgp1_production/api-tose-blog
        git pull origin master
        pnpm install
        pnpm build
        pm2 restart api-tose-blog-2023
        ENDSSH